### ISSUE TITLE
command run details

### ISSUE THREAD

**Issue by orangecat-sjz** [yangalan123/Amortized-Interpretability#2] opened 2024-01-22 06:19 UTC
Hello, I want to test the stability of the shapley value calculation you mentioned in the paper, which is the table1 that leads to the problem. I tried the method given in the readme, but there were always path problems, such as when using the thermostat folder you provided. The run_explainer.py file is missing. Besides there is no /yelp_polarity folder in the folder cloned using the latest thermostat repository, the config is missing. Then I tried to copy the /yelp_polarity folder to new thermostat folder's /configs. However parameter 'path' and 'dataset_dir' in 'svs-3600.jsonnet' make me feel helpless. So how can I run the command given in the readme: bash run.sh task=yelp_polarity model=bert explainer=svs-3600 seed=1 batch_size=1 device=0 command.

**Comment by yangalan123** [comment] 2024-01-22 23:18
Hi, thanks for raising this issue. There seems to be some problem when using the official `thermostat` library -- For reproduction purposes, I have uploaded my cached local version in the latest commit, and you should remove your existing thermostat installation, and install using my local cached version under `thermostat`. Let me know if that does not work -- I no longer have access to the previous computation resources I used, so it is a bit hard for me to run testing for you on my side. But I will try my best to assist your reproduction.

**Comment by orangecat-sjz** [comment] 2024-01-24 05:30
Thank you for taking the time to reply. However, I am still encountering issues when running the 'run.sh' file under the new 'thermostat' folder. The error message indicates a failure to create 'experiment_path' at line 29 of 'run_explainer.py' in the 'read_config' function. I think the issue may be related to the 'path' and 'root_dir' settings in the 'svs-3600.jsonnet' file. Could you please provide detailed instructions on how to write these two path parameters? I greatly appreciate it.
________________________________
发件人: Chenghao (Alan) Yang ***@***.***>
发送时间: 2024年1月23日 7:18
收件人: yangalan123/Amortized-Interpretability ***@***.***>
抄送: orangecat-sjz ***@***.***>; Author ***@***.***>
主题: Re: [yangalan123/Amortized-Interpretability] command run details (Issue #2)


Hi, thanks for raising this issue. There seems to be some problem when using the official thermostat library -- For reproduction purposes, I have uploaded my cached local version and you should remove your existing thermostat installation, and install using my local cached version under thermostat. Let me know if that does not work -- I no longer have access to the previous computation resources I used, but I will try my best to assist your reproduction.

―

**Comment by orangecat-sjz** [comment] 2024-01-24 06:15
oh, I'm sorry the problem has been solved.So sorry to bother you.
________________________________
发件人: Chenghao (Alan) Yang ***@***.***>
发送时间: 2024年1月23日 7:18
收件人: yangalan123/Amortized-Interpretability ***@***.***>
抄送: orangecat-sjz ***@***.***>; Author ***@***.***>
主题: Re: [yangalan123/Amortized-Interpretability] command run details (Issue #2)


Hi, thanks for raising this issue. There seems to be some problem when using the official thermostat library -- For reproduction purposes, I have uploaded my cached local version and you should remove your existing thermostat installation, and install using my local cached version under thermostat. Let me know if that does not work -- I no longer have access to the previous computation resources I used, but I will try my best to assist your reproduction.

―

**Comment by yangalan123** [comment] 2024-01-24 06:38
So do you mean the problem has been solved? Or do you need a bit more time to reproduce my experiment results?

**Comment by orangecat-sjz** [comment] 2024-01-24 07:15
I encountered another problem the yelp_polarity data set needs to be downloaded. When I tried to run download_data.py, I used the -c configs/yelp_polarity/bert/svs-3600.jsonnet parameter, but the error message said that the data set could not be found(ConnectionError: Couldn't reach 'yelp_polarity' on the Hub (ConnectTimeout)). How could I download it correctly?  Or how to download it directly from Hugging Face to the local and then move it to the corresponding location
________________________________
发件人: Chenghao (Alan) Yang ***@***.***>
发送时间: 2024年1月24日 14:38
收件人: yangalan123/Amortized-Interpretability ***@***.***>
抄送: orangecat-sjz ***@***.***>; Author ***@***.***>
主题: Re: [yangalan123/Amortized-Interpretability] command run details (Issue #2)


So do you mean the problem has been solved? Or do you need a bit more time to reproduce my experiment results?

―

**Comment by yangalan123** [comment] 2024-01-24 07:28
Sorry it is already pretty late on my side and I plan to sleep -- I will
take a look after I wake up if the problem persists.

Best,
Chenghao

**Comment by yangalan123** [comment] 2024-01-25 23:02
I tried a bit and on my side, this `download_data.py` with your command line running arguments runs well -- I guess this ConnectionTimeout problem may be due to your network environment.  I am not sure whether I have good methods to figure out the network problem.  Sorry about that.

**Comment by orangecat-sjz** [comment] 2024-01-26 06:31
I have successfully reproduced the MNLI task, which is relatively short. The previous failure in downloading the dataset was due to the wrong version of the ‘transformer' and ‘datasets' libraries caused by the order of library installation with pip -r. Thank you again for your reply.
发件人: Chenghao (Alan) Yang ***@***.***>
日期: 星期五, 2024年1月26日 07:02
收件人: yangalan123/Amortized-Interpretability ***@***.***>
抄送: orangecat-sjz ***@***.***>, Author ***@***.***>
主题: Re: [yangalan123/Amortized-Interpretability] command run details (Issue #2)


I tried a bit and on my side, this download_data.py with your command line running arguments runs well -- I guess this ConnectionTimeout problem may only be due to your network environment. I am not sure whether I have good methods to figure out the network problem. Sorry about that.

―

**Comment by yangalan123** [comment] 2024-01-26 06:41
Great! Glad to hear the problem gets resolved on your side. Then maybe we can close this issue?

**Closed as completed** 2024-01-26 08:01 UTC
